### ISSUE TITLE
Need to integrate a log forwarder in the base image

### ISSUE THREAD

**Issue by gozer** [mozilla/nubis-base#12]
For now, to keep things modular and simple, my vote would go with:

http://www.fluentd.org/

**Comment by bbh-node** [comment]
It's on the puppet module forge, too.

https://forge.puppetlabs.com/srf/fluentd

This would replace syslogd?

**Comment by bhourigan** [comment]
Would this replace syslogd? What benefits does it have over syslogd?

Good news it already has a puppet module - https://forge.puppetlabs.com/srf/fluentd

**Comment by gozer** [comment]
No, its a generic and modular log forwarder. Not something to replace syslog, but on top of it.

The idea is that we need something that can take all logs produced on the nodes, syslog, application logs, etc, and ship them reliably, relatively in real-time to something centralized.

Fluentd is one of many things like Kafka that lets us do that quick, easily and with a good dose of available plugins.

**Comment by bhourigan** [comment]
Very cool. I read some more about it last night, and in my pull request to nubis-puppet I configured the manifest to ingest the default Ubuntu syslogs.

**Comment by bhourigan** [comment]
Fluentd is included in the base AMIs now
