### ISSUE TITLE
Need to integrate confd in the base image

### ISSUE THREAD

**Issue by gozer** [mozilla/nubis-base#2]

**Comment by bhourigan** [comment]
I added ajcrowe/confd@0.2.0 in e757fcd, but no manifest references. how can we bootstrap the initial node list?

**Comment by gozer** [comment]
I am working on that part on my branch.

Once finished, confd will be able to just talk to localhost. I'll show you tomorrow how the bootstrapping works. It's all in nubis-consul and nubis-base land.

The problem with that puppet module is that its strangely built and doesn't download the client binaries like the consul module does, unfortunately.
