### ISSUE TITLE
Need to look into building a base image from Amazon Linux AMIs as well as Ubuntu.

### ISSUE THREAD

**Issue by gozer** [mozilla/nubis-base#27]

**Comment by bhourigan** [comment]
I fixed up packer-bootstrap to handle Amazon Linux and it does the job with a few ugly hacks, although, ran into a upstream puppet issue:

   amazon-us-west-2: Error: Module dnsmasq is not supported on Amazon at /tmp/packer-puppet-masterless/module-0/dnsmasq/manifests/params.pp:33 on node ip-10-213-174-27.us-west-2.compute.internal
    amazon-us-west-2: Error: Module dnsmasq is not supported on Amazon at /tmp/packer-puppet-masterless/module-0/dnsmasq/manifests/params.pp:33 on node ip-10-213-174-27.us-west-2.compute.internal

**Comment by bhourigan** [comment]
We now have full Amazon linux support
