### ISSUE TITLE
Need to cleanly solve the MTA issue in the base image (sendmail is not great)

### ISSUE THREAD

**Issue by gozer** [mozilla/nubis-base#3]

**Comment by bbh-node** [comment]
I'd vote for postfix, it's pretty robust and very simple to configure. (no m4 config preprocessor!)

**Comment by bhourigan** [comment]
I'd vote for postfix.

**Comment by gozer** [comment]
Postfix gets my vote as well.

Eventually, we'll need to make it use a smart relay via confd/consul, but good to go

**Comment by bhourigan** [comment]
Hmm.. actually, nullmailer is a fantastic dumb MTA, but we'll need a relay host to funnel all email through.  It's too dumb to send outbound email directly and queue, etc.

**Comment by floatingatoll** [comment]
I think postfix in the satellite configuration is best.

We don't want local application failures due to temporary blips between an
instance and its smarthost, whether that's smtp.mozilla.org or an internal
10.x IP or a third-party relay service or whatever.

 - R.

**Comment by tinnightcap** [comment]
I vote Postfix also

**Comment by bhourigan** [comment]
Postfix is now shipping in base
