### ISSUE TITLE
We need a tool to drive packer and publish AMIs (and possibly other outputs) into Consul

### ISSUE THREAD

**Issue by gozer** [mozilla/nubis-base#32]

**Comment by bhourigan** [comment]
Could you point me to some docs, etc for the Consul API that'll be accessed to push this data in? Where in Consul should it be stored?

**Comment by gozer** [comment]
https://www.consul.io/docs/agent/http.html

For now, I'd look at how I've structured stuff in there already.

But it's not good enough, as it assumes a single AMI per region, per project, per build.

With the instance types and os types, that's not enough.

Change at will to what you think makes sense

**Comment by RichardWeiss** [comment]
Is this a per-service limitation or for the whole environment?  If we're using fully baked AMI's to spin up instances it's hard to guess how many we'll need per service.  A complex service could have a dozen or more components running on EC2 and we will have many services running.

**Comment by bhourigan** [comment]
> Is this a per-service limitation or for the whole environment? If we're using fully baked AMI's to spin up instances it's hard to guess how many we'll need per service. A complex service could have a dozen or more components running on EC2 and we will have many services running.

This is way ahead of us, we're discussing internal build semantics within the base image and it not yet applicable to service deployment.

**Comment by bhourigan** [comment]
going another route
